# Generated by Django 5.0.6 on 2024-12-16 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminfo',
            name='type_storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_infos', to='warehouseapp.typestorage'),
        ),
    ]
